#!/usr/bin/python3
# -*- coding: utf-8 -*-
import random
import math

def isPrime(x):
    count = 0
    for i in range(int(x/2)):
        if x % (i+1) == 0:
            count = count+1
    return count == 1

@@Generation_cles@@
    



